services:
  # Override backend for development - DB와 Redis 준비 대기
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Override frontend for development - Backend 준비 대기
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
